require "meteofrance_api/models/forecast"
require "meteofrance_api/models/place"
require "meteofrance_api/models/rain"
require "meteofrance_api/models/warning_current_phenomenons"
require "meteofrance_api/models/warning_full.rb"
